# 5-1 Numpy 科学计算

In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[2,2,3],[7,2,9]]) #if the list of list is 3,3,4 this can only be 1 dimension

## 基本方法
develope Based on C  
ndim 维度  
shape 行数和列数  
size 元素个数  
itemsize 每个元素的字节大小  
dtype 数据类型  
f.astype()  
g.tolist()  

In [3]:
a

array([1, 2, 3])

In [7]:
b

array([[1, 2, 3],
       [2, 2, 3],
       [7, 2, 9]])

In [4]:
b.ndim

1

In [8]:
b.shape

(3, 3)

In [12]:
a.itemsize

4

In [13]:
b.size

6

In [14]:
c = np.array([[1.2,2,3],[2,2,3]])
c.dtype

dtype('float64')

In [9]:
b

array([[1, 2, 3],
       [2, 2, 3],
       [7, 2, 9]])

2

2

## 数组切片

### 2 维数组

In [35]:
b = np.array([[1,2,3,5],[2,2,3,9],[7,2,9,0]]) #if the list of list is 4,4,5 this can only be 1 dimension

In [39]:
b

array([[1, 2, 3, 5],
       [2, 2, 3, 9],
       [7, 2, 9, 0]])

In [37]:
b[0,1]

2

In [38]:
b[0][1]

2

####  a[ ]  a[ ][ ] 2个括号！注意切片是不同的！！！ 但是选取单个元素是一样的

In [40]:
b[:,0:2]

array([[1, 2],
       [2, 2],
       [7, 2]])

In [41]:
b[:][0:2]

array([[1, 2, 3, 5],
       [2, 2, 3, 9]])

In [42]:
b[0:2]

array([[1, 2, 3, 5],
       [2, 2, 3, 9]])

In [21]:
b[2,1]

2

也算索引也算切片

In [22]:
b[[2,1]]

array([[7, 2, 9],
       [2, 2, 3]])

In [48]:
b[[2,1],[0,1]] #row pick 2 1 column pick 0 1 类似于点菜的方法

array([7, 2])

### 3 维数组

In [44]:
arr3d = np.array([[[1, 2, 3,0], [1,4, 5, 6]], [[2,7, 8, 9], [3,10, 11, 12]]])
arr3d

array([[[ 1,  2,  3,  0],
        [ 1,  4,  5,  6]],

       [[ 2,  7,  8,  9],
        [ 3, 10, 11, 12]]])

In [20]:
arr3d[0,1] #在多维数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）

array([4, 5, 6])

In [31]:
arr3d[0,1,1]

5

In [24]:
arr3d[0][1]

array([4, 5, 6])

In [26]:
arr3d[0][1][1]

5

In [32]:
arr3d[0:2,0:2,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [33]:
arr3d[0:2][0:2][0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[[0,1],[0,1],[0,1]]


array([ 1, 10])

## 数组创建
1. np.array([[3,4],[1,2]])
2. np.zeros((3,3))
3. np.ones((2,3))
4. np.eye(2)
5. np.full((3,3),666)
6. np.empty((4,4))
7. 利用 arragen, linspace:
    np.arange(1,30,3)
    then you can reshape it np.arange(1,30,3).reshape(2,5)
    np.linspace(1,10,10) 前面数据等分 不是步长
    np.arange(1,10,1) not the same
    same as: np.linsapce(1,9,9)
8. np.random.randint(1,10,(3,3))  [range) size 是伪随机数 需要修改seed  
9. np.random.randn(2,3)
10. np.nan  not a number np.inf infinity number 


## 1.3 数组操作
1. 常数  
np.e np.pi, ni.nan np.inf
2. element calculate
[A,B]+C=[A+C,B+C]
3. np.dot(a,b) or a.dot(b)  
np.dot(b,a)!=np.dot(a,b)
[M,N] DOT [T,Q] = [M,Q]

# 5-2 
课件复制过来

# 5-3 

## 1. 数组拼接
1. vstack: 垂直拼接
2. hstack : 水平拼接
3. concatenate  
    axis设定数据层次


In [49]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[1,1,1],[2,2,2]])

In [52]:
np.vstack((a1,a2,a1))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.hstack((a1,a2,a1))

array([[1, 2, 3, 1, 1, 1, 1, 2, 3],
       [4, 5, 6, 2, 2, 2, 4, 5, 6]])

In [54]:
np.column_stack((a1,a2))

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [55]:
np.row_stack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [58]:
np.concatenate((a1,a2),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [59]:
np.concatenate?

## 2. 数组分列  
均分分列
hsplit：水平切分
vsplit：垂直切分
split：自定义均分    

不对称分列  
例 np.split(A, [1, 3], axis = 1)
第二个参数代表下标，在那些下标之前进行分列
[0], [1,2], [3]
例 np.array_split(A, 3, axis=1)
第二个参数代表份数 前多后少
类似除法的 商+余数(均分) [0,1], [2], [3]

In [60]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.hsplit(A,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [68]:
np.vsplit(A,[2,1])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([], shape=(0, 4), dtype=int32),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [66]:
np.split(A,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [67]:
np.split(A,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]), array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [70]:
np.array_split(A,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

## 3. 数组变形   
reshape ：副本
shape ：本身
ravel ：展平(本身)
flatten ：展平(副本)
transpose / .T ： 转置
newaxis ：维度增加

In [77]:
B= np.arange(16)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
B.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
B.shape # 数组本身并没改变

(16,)

In [86]:
B.shape=(2,2,4) #强行修改

In [87]:
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [90]:
B1=B.ravel()
B1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
B2=B.flatten()
B2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [92]:
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [93]:
B1[0]=99
B1

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
B

array([[[99,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [96]:
B2[0]=666
B2

array([666,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [97]:
B

array([[[99,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [100]:
B.shape=(4,4)
B

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
B.transpose() 
B.T # same

array([[99,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [106]:
B[np.newaxis,:,:]

array([[[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [107]:
B[:,np.newaxis,:] #在中间层加了个维度 即：每个元素 例如[99,1,2,3] 外加括号变为[[99,1,2,3]]

array([[[99,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]],

       [[12, 13, 14, 15]]])

In [109]:
B[:,:,np.newaxis] #在最内层增加了一个维度
 #3 different things! increase dimensions

array([[[99],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]]])

In [111]:
#same as 
B.reshape(1,4,4) #(4,1,4) (4,4,1)

array([[[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## 4. 课堂练习

创建一个5x5的矩阵，其中每行的数值范围依次从0到4

In [134]:
b=np.array([i for i in range(5)]*5).reshape(5,5)
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

创建5x5的矩阵，其中只有对角线上数值依次从0到4，
其余为0

In [128]:
t = np.arange(5)
t

array([0, 1, 2, 3, 4])

In [138]:
t*np.eye(5)

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])

随机生成一个包括13个元素的数组，找到最接近其均值
的元素并返回值和位置

In [159]:
t=np.random.random(13)
t

array([0.66595928, 0.1123265 , 0.2891921 , 0.40829272, 0.41263936,
       0.6098776 , 0.79851341, 0.8925589 , 0.37362396, 0.70255562,
       0.25711571, 0.7464818 , 0.50477692])

In [160]:
a=t.mean()

In [161]:
ind=(np.abs(t-a)).argmin()

In [162]:
t[7]

0.8925589036465112

# 5-4 NumPy数据操作：筛选 排序 存取

## 1. 数据筛选  
利用条件表达式和布尔运算符  
A >5  
A[A>5]  
any和all可以判断布尔型数组的结果  
a = np.array([False, False, True, False])  
a.any() / a.all()  
where  
克服列表生成式无法应用于高维数组的局限

In [164]:
a = np.random.randint(1,10,9).reshape(3,3)
a>5

array([[False, False, False],
       [ True, False,  True],
       [False, False, False]])

In [165]:
a[a>5]

array([8, 7])

In [166]:
a*(a>5)

array([[0, 0, 0],
       [8, 0, 7],
       [0, 0, 0]])

In [167]:
b=a>5

In [172]:
from IPython import display

In [174]:
b.all()
b.any() # 是不是全为真或者有一个真

True

In [176]:
b.all(axis=1)

array([False, False, False])

In [178]:
a = np.random.randint(-9,10,9).reshape(3,3)
a

array([[ 4,  7, -1],
       [ 0,  4,  9],
       [ 1, -2,  4]])

In [179]:
np.where(a>0,-a,-a)

array([[-4, -7,  1],
       [ 0, -4, -9],
       [-1,  2, -4]])

## 2. 数据排序  
1. np.sort  
    针对列 axis = 0  
    针对行 axis = 1  
2. order 参数  
    数组自定义    
    排序规则自定义  

In [181]:
a = np.random.randint(-9,10,16).reshape(4,4)
a

array([[-6, -4,  0,  7],
       [ 2, -9, -8, -8],
       [ 6,  6,  2, -6],
       [-6, -3,  6, -7]])

In [184]:
a.sort(axis=0)
a

array([[-9, -8, -8,  2],
       [-7, -6, -3,  6],
       [-6, -4,  0,  6],
       [-6,  2,  6,  7]])

### 自定义数组的介绍

In [5]:
dtype =[('name','U10'),('height',float),('age',int)]
values=[('里斯',1.8,41),('王五',1.3,21),('王2',1.6,9)]

In [6]:
a= np.array(values,dtype=dtype)
a

array([('里斯', 1.8, 41), ('王五', 1.3, 21), ('王2', 1.6,  9)],
      dtype=[('name', '<U10'), ('height', '<f8'), ('age', '<i4')])

In [187]:
a.sort(order ='age')

In [188]:
a

array([('王2', 1.6,  9), ('王五', 1.3, 21), ('里斯', 1.8, 41)],
      dtype=[('name', '<U10'), ('height', '<f8'), ('age', '<i4')])

## 3. 数组存取  
1. 以文件格式存取   
    保存数组到文件 tofile(文件路径，间隔符，格式)  
    从文件读取数组 genformat(文件路径，间隔符)  
2. 以二进制格式存取   
    np.save
    np.load 

In [192]:
np.genfromtxt?

In [194]:
np.genfromtxt(fname='D:\Files\ML&DL\DC_Castle\Project\Cahpter5\example.txt',delimiter=',')

array([[ 1.,  2.,  3.,  4.],
       [ 5., nan, nan,  6.],
       [ 7.,  8., nan,  9.]])

In [2]:
A = np.random.randint(-9,10,16).reshape(4,4)
A

array([[ 7,  9, -6, -2],
       [ 3, -8,  6,  8],
       [ 0,  6, -1,  1],
       [-5, -6,  0, -5]])

In [197]:
A.tofile(r'D:\Files\ML&DL\DC_Castle\Project\Cahpter5\example1.txt',sep=',')

In [3]:
a.tofile(r'D:\Files\ML&DL\DC_Castle\Project\Cahpter5\example2.txt',sep=',') #tofile 对自定义的数组不接受 需要用2进制存放

NameError: name 'a' is not defined

In [8]:
np.save(r'D:\Files\ML&DL\DC_Castle\Project\Cahpter5\A',A)

In [9]:
B=np.load(r'D:\Files\ML&DL\DC_Castle\Project\Cahpter5\A.npy')
B

array([[ 7,  9, -6, -2],
       [ 3, -8,  6,  8],
       [ 0,  6, -1,  1],
       [-5, -6,  0, -5]])

批量的存储

In [10]:
np.savez(r'D:\Files\ML&DL\DC_Castle\Project\Cahpter5\arr',a=A,b=B)

In [12]:
arr =np.load(r'D:\Files\ML&DL\DC_Castle\Project\Cahpter5\arr.npz')
arr

In [20]:
arr['a']

array([[ 7,  9, -6, -2],
       [ 3, -8,  6,  8],
       [ 0,  6, -1,  1],
       [-5, -6,  0, -5]])

## 课堂练习

### 如何找到一个数组中出现频率最高的值?第二高的呢


In [21]:
a = np.random.randint(1,10,20)
a

array([1, 3, 3, 5, 5, 3, 3, 8, 9, 9, 4, 1, 3, 1, 6, 4, 7, 1, 5, 4])

In [22]:
set(a) #remove duplicate

{1, 3, 4, 5, 6, 7, 8, 9}

In [26]:
temp=[[np.sum(a==i),i] for i in set(a)] 
temp

[[4, 1], [5, 3], [3, 4], [3, 5], [1, 6], [1, 7], [1, 8], [2, 9]]

In [29]:
sorted(temp)[-2][1] #not using np.sort because you need to set rules 

1

In [31]:
np.bincount(a).argmax()+1

4

### 用numpy创建一个自定义的数据结构，能够表示出一个像素点的位置坐标(x,y)以及对应的色彩(RGB)

In [32]:
dt = [('position',[('x',int),('y',int)]),('color',[('r',int),('g',int),('b',int)])]

In [34]:
data = np.array(((0,0),(100,255,0)),dtype=dt)
data

array(((0, 0), (100, 255, 0)),
      dtype=[('position', [('x', '<i4'), ('y', '<i4')]), ('color', [('r', '<i4'), ('g', '<i4'), ('b', '<i4')])])

# 5-5 pandas基础 Series  
1. Numpy、Pandas比较  
Pandas库的数据处理功能建立在numpy库的基础上,两者相辅相成   
Numpy适用于处理基本的数值计算，以矩阵运算为主  
Pandas适用于处理包含不同变量类型（整数、浮点）的表格数据，和Matlab不同，python的索引是从0开始
2. pandas数据结构简介
Pandas的核心为两大数据结构，数据处理都是围绕着这两种结构进行的：  
Series  
DataFrame  
Series这类数据结构用于存储一个序列的一维数据  
DataFrame用于存储多维数据  
两者的奇特之处是将Index（索引）对象和标签整合到自己的结构中  
3. Series对象
pandas库的Series对象用来表示一维数据结构，类似array
它的内部结构很简单，由两个相互关联的数组组成，其中主数组用来存放数据
主数组的每个元素都有一个与之相关联的标签，这些标签存储在另外一个叫做
Index的数组中


### Series基本操作
Series创建  
自定义索引  
支持Series创建的数据结构类型  
数据访问 标签 / 键  
查找尽量用索引（标签），键不稳定  
赋值  
筛选  

In [35]:
import pandas as pd

In [37]:
a = pd.Series([1,2,3,4],index = ['a','b','c','d'])
a

a    1
b    2
c    3
d    4
dtype: int64

In [38]:
a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [39]:
a.values

array([1, 2, 3, 4], dtype=int64)

In [40]:
# 2 ways to search 
a['a']
a[0]

1

In [41]:
b = pd.Series([1,2,3,4],index = ['a','a','c','d'])
b

a    1
a    2
c    3
d    4
dtype: int64

In [42]:
b['a']

a    1
a    2
dtype: int64

In [46]:
b[0] #这样则会报错 
#两个连续的索引重复
#会报IndexERROR

IndexError: 0

In [47]:
c = pd.Series([1,2,3,4],index = ['a','c','a','d']) #list tuple dict all can be created to Series
c

a    1
c    2
a    3
d    4
dtype: int64

In [45]:
c[0]

1

In [48]:
c={'red':200,'blue':1000,'yellow':500,'orange':1000}
d=pd.Series(c)
d

red        200
blue      1000
yellow     500
orange    1000
dtype: int64

In [51]:
d[d>200]

blue      1000
yellow     500
orange    1000
dtype: int64

### Series的运算 
Series之间的运算通过匹配标签进行操作

In [53]:
mydict = {'red':400,'blue':1000,'yellow':500,'orange':1000}
myseries=pd.Series(mydict)
mydict2 = {'red':2000,'blue':1000,'black':500}
myseries2=pd.Series(mydict2)


In [54]:
myseries+myseries2

black        NaN
blue      2000.0
orange       NaN
red       2400.0
yellow       NaN
dtype: float64

### series常用方法
1. unique    
    去重，返回values的唯一值  
2. value_counts
    去重，统计元素出现次数  
3. isin
    判断从属关系，可用于筛选数据，参数必须是列表  

In [57]:
b = pd.Series([1,2,3,4,1,4],index=['a','r','d','b','c','d'])
b

a    1
r    2
d    3
b    4
c    1
d    4
dtype: int64

In [58]:
b.unique() #become an array

array([1, 2, 3, 4], dtype=int64)